from __future__ import annotations

ENTITY_TYPES = {
    "Material",
    "Substance",
    "Process",
    "Equipment",
    "Property",
    "Parameter",
    "Condition",
    "Experiment",
    "Publication",
    "TechnologySolution",
    "Result",
    "Conclusion",
    "Limitation",
    "Facility",
    "Organization",
    "Expert",
}

RELATION_TYPES = {
    "has_subprocess",
    "replaced_by",
    "affects_property",
    "has_limitation",
    "has_quality_requirement",
    "has_distribution_requirement",
    "has_expected_result",
    "based_on",
    "applies_to",
    "uses_technology",
    "produces_output",
    "requires_expertise",
    "uses_equipment",
    "studies",
    "fed_through",
    "depends_on",
    "operates_at_condition",
    "measured_property",
    "operates_between",
    "validated_by",
    "performed_by",
    "uses_material",
    "described_in",
    "supported_by",
    "authored_by",
    "affiliated_with",
    "used_in_facility",
    "contradicts",
}

REQUIRED_SAMPLE_FIELDS = {
    "sample_id",
    "chunk_id",
    "document_id",
    "source_path",
    "text",
    "entities",
    "relations",
}
